### ISSUE TITLE
Optical flow processing code

### ISSUE THREAD

**Issue by height921** [ericyinyzy/MTN_trajectory#7]
Hello, author, can you open source the code of optical flow processing? I would like to do experiments on other data sets. If possible, I would be very grateful.

**Comment by ericyinyzy** [comment]
Hi, we extract optical flow using [https://github.com/princeton-vl/RAFT](RAFT) trained with the KITTI dataset.  Currently, we are not able to release the optical flow processing codes since the original data are not available.  All optical flow processing details are illustrated in section 2.1 and **Implementation Details**.
